# Generated by Django 5.1.7 on 2025-04-05 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cartitems',
            new_name='Cartitem',
        ),
    ]
